name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке
on:
  push:
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@v4
      # Устанавливаем python нужной версии
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install requirements
        # Устанавливаем зависимости
        run: | 
          pip install -r fastapi/requirements.txt
          pip install coverage
      - name: Run tests
        run: coverage run src/tests.py
      - name: Tests report
        run: coverage report